### ISSUE TITLE
'DynGraph' object has no attribute '_node'

### ISSUE THREAD

**Issue by pedrocklein** [GiulioRossetti/dynetx#32]
Hi.

I am getting this message every time that I want to add an interaction to an empty graph.  Here is a snapshot of my code:

`import dynetx as dn`
`g = dn.DynGraph(edge_removal=True)`
`g.add_interaction(u=1, v=2, t=0)`

And the error:

AttributeError: 'DynGraph' object has no attribute '_node'

I installed the dynetx with "pip install dynetx".

**Comment by GiulioRossetti** [comment]
Can you check the version of networkx installed on your system? Are you using Python 2.7 or 3?

**Comment by pedrocklein** [comment]
Hi,

I am using networkx with the '1.9.1' version and Python 2.7

**Comment by GiulioRossetti** [comment]
Ok, the issue is due to the networkx version.

DyNetX requires networkx>=2.x (as listed in requirements.txt).
The internal representation of graphs significantly changed in networkx 2.0 w.r.t. the previous major release: this project extends the functionalities offered by the latest version of such package.

**Comment by saket-v7** [comment]
I am using networkx-2.2 and python 2.7.15 rc1 version, but still this same error is showing
