### ISSUE TITLE
Transforming a snapshot into networkx graph

### ISSUE THREAD

**Issue by AlexisPister** [GiulioRossetti/dynetx#82]
Hi,

Great job for this very useful library !

I have imported my data into a DynGraph object. I would like now to apply some networkx algorithm for each snapshot of the data separately, is there a way to easily transofrm each snapshot into a networkx graph ? Because even if a DynGraph object inherit from the nx.Graph class, the behaviours are not exactly the same.

Thanks

**Comment by GiulioRossetti** [comment]
Hi,

thanks for your kind words, I'm happy DyNetX has been useful to you.

Indeed you can obtain a slice from your temporal graph using the method time_slice(from, to) (see the docs here: https://dynetx.readthedocs.io/en/latest/tutorial.html#slicing-a-dynamic-network). So, if you are interested in accessing a single snapshot you can call g.time_slice(temporal_id).

Such a method returns a DynGraph instance where edges/nodes are kept if they appear in the window [from, to]: since DynGraphs extends nx.Graph you can directly cast such an object to its parent class.

Hope this helps.

Best,
Giulio

**Comment by AlexisPister** [comment]
Hi,

I was not aware of type casting from a child class to a parent class object.

I did it the following way :
```
snapshot.__class__ = nx.Graph
```
snapshot being a DynGraph object

It seems to currently work for my usecase, but it looks a bit like a hack.

Thanks for the help !
Alexis

**Comment by GiulioRossetti** [comment]
If you like something more "pythonic" you can do something like:

`F = nx.Graph(H.edges)`

with H being a DynGraph instance.
